// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: bookshop.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Book struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	PageCount     int32                  `protobuf:"varint,3,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	Language      *string                `protobuf:"bytes,4,opt,name=language,proto3,oneof" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_bookshop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_bookshop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_bookshop_proto_rawDescGZIP(), []int{0}
}

func (x *Book) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Book) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Book) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *Book) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

type GetBookListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookListRequest) Reset() {
	*x = GetBookListRequest{}
	mi := &file_bookshop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookListRequest) ProtoMessage() {}

func (x *GetBookListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bookshop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookListRequest.ProtoReflect.Descriptor instead.
func (*GetBookListRequest) Descriptor() ([]byte, []int) {
	return file_bookshop_proto_rawDescGZIP(), []int{1}
}

type GetBookListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Book                `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookListResponse) Reset() {
	*x = GetBookListResponse{}
	mi := &file_bookshop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookListResponse) ProtoMessage() {}

func (x *GetBookListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bookshop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookListResponse.ProtoReflect.Descriptor instead.
func (*GetBookListResponse) Descriptor() ([]byte, []int) {
	return file_bookshop_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookListResponse) GetBooks() []*Book {
	if x != nil {
		return x.Books
	}
	return nil
}

var File_bookshop_proto protoreflect.FileDescriptor

const file_bookshop_proto_rawDesc = "" +
	"\n" +
	"\x0ebookshop.proto\"\x81\x01\n" +
	"\x04Book\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"page_count\x18\x03 \x01(\x05R\tpageCount\x12\x1f\n" +
	"\blanguage\x18\x04 \x01(\tH\x00R\blanguage\x88\x01\x01B\v\n" +
	"\t_language\"\x14\n" +
	"\x12GetBookListRequest\"2\n" +
	"\x13GetBookListResponse\x12\x1b\n" +
	"\x05books\x18\x01 \x03(\v2\x05.BookR\x05books2G\n" +
	"\tInventory\x12:\n" +
	"\vGetBookList\x12\x13.GetBookListRequest\x1a\x14.GetBookListResponse\"\x00B\x0eZ\fpb/inventoryb\x06proto3"

var (
	file_bookshop_proto_rawDescOnce sync.Once
	file_bookshop_proto_rawDescData []byte
)

func file_bookshop_proto_rawDescGZIP() []byte {
	file_bookshop_proto_rawDescOnce.Do(func() {
		file_bookshop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bookshop_proto_rawDesc), len(file_bookshop_proto_rawDesc)))
	})
	return file_bookshop_proto_rawDescData
}

var file_bookshop_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bookshop_proto_goTypes = []any{
	(*Book)(nil),                // 0: Book
	(*GetBookListRequest)(nil),  // 1: GetBookListRequest
	(*GetBookListResponse)(nil), // 2: GetBookListResponse
}
var file_bookshop_proto_depIdxs = []int32{
	0, // 0: GetBookListResponse.books:type_name -> Book
	1, // 1: Inventory.GetBookList:input_type -> GetBookListRequest
	2, // 2: Inventory.GetBookList:output_type -> GetBookListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bookshop_proto_init() }
func file_bookshop_proto_init() {
	if File_bookshop_proto != nil {
		return
	}
	file_bookshop_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bookshop_proto_rawDesc), len(file_bookshop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookshop_proto_goTypes,
		DependencyIndexes: file_bookshop_proto_depIdxs,
		MessageInfos:      file_bookshop_proto_msgTypes,
	}.Build()
	File_bookshop_proto = out.File
	file_bookshop_proto_goTypes = nil
	file_bookshop_proto_depIdxs = nil
}
