// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: booklist_service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBookListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetBookListRequest) Reset() {
	*x = GetBookListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booklist_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookListRequest) ProtoMessage() {}

func (x *GetBookListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booklist_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookListRequest.ProtoReflect.Descriptor instead.
func (*GetBookListRequest) Descriptor() ([]byte, []int) {
	return file_booklist_service_proto_rawDescGZIP(), []int{0}
}

type GetBookListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookList *BookList `protobuf:"bytes,1,opt,name=book_list,json=bookList,proto3" json:"book_list,omitempty"`
}

func (x *GetBookListResponse) Reset() {
	*x = GetBookListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_booklist_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookListResponse) ProtoMessage() {}

func (x *GetBookListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booklist_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookListResponse.ProtoReflect.Descriptor instead.
func (*GetBookListResponse) Descriptor() ([]byte, []int) {
	return file_booklist_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetBookListResponse) GetBookList() *BookList {
	if x != nil {
		return x.BookList
	}
	return nil
}

var File_booklist_service_proto protoreflect.FileDescriptor

var file_booklist_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x62, 0x6f, 0x6f, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x61, 0x68, 0x61, 0x6e, 0x73,
	0x65, 0x72, 0x61, 0x2e, 0x67, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x12, 0x62, 0x6f, 0x6f, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12,
	0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x4e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x09, 0x62, 0x6f, 0x6f,
	0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73,
	0x61, 0x68, 0x61, 0x6e, 0x73, 0x65, 0x72, 0x61, 0x2e, 0x67, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x32, 0x80, 0x01, 0x0a, 0x0f, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x73, 0x61, 0x68, 0x61, 0x6e, 0x73, 0x65, 0x72,
	0x61, 0x2e, 0x67, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x73, 0x61,
	0x68, 0x61, 0x6e, 0x73, 0x65, 0x72, 0x61, 0x2e, 0x67, 0x6f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x12, 0x09, 0x2f, 0x62, 0x6f, 0x6f,
	0x6b, 0x6c, 0x69, 0x73, 0x74, 0x42, 0x05, 0x5a, 0x03, 0x70, 0x62, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_booklist_service_proto_rawDescOnce sync.Once
	file_booklist_service_proto_rawDescData = file_booklist_service_proto_rawDesc
)

func file_booklist_service_proto_rawDescGZIP() []byte {
	file_booklist_service_proto_rawDescOnce.Do(func() {
		file_booklist_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_booklist_service_proto_rawDescData)
	})
	return file_booklist_service_proto_rawDescData
}

var file_booklist_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_booklist_service_proto_goTypes = []interface{}{
	(*GetBookListRequest)(nil),  // 0: sahansera.gogrpc.GetBookListRequest
	(*GetBookListResponse)(nil), // 1: sahansera.gogrpc.GetBookListResponse
	(*BookList)(nil),            // 2: sahansera.gogrpc.BookList
}
var file_booklist_service_proto_depIdxs = []int32{
	2, // 0: sahansera.gogrpc.GetBookListResponse.book_list:type_name -> sahansera.gogrpc.BookList
	0, // 1: sahansera.gogrpc.BookListService.GetBookList:input_type -> sahansera.gogrpc.GetBookListRequest
	1, // 2: sahansera.gogrpc.BookListService.GetBookList:output_type -> sahansera.gogrpc.GetBookListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_booklist_service_proto_init() }
func file_booklist_service_proto_init() {
	if File_booklist_service_proto != nil {
		return
	}
	file_booklist_msg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_booklist_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_booklist_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_booklist_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booklist_service_proto_goTypes,
		DependencyIndexes: file_booklist_service_proto_depIdxs,
		MessageInfos:      file_booklist_service_proto_msgTypes,
	}.Build()
	File_booklist_service_proto = out.File
	file_booklist_service_proto_rawDesc = nil
	file_booklist_service_proto_goTypes = nil
	file_booklist_service_proto_depIdxs = nil
}
